# Generated by Django 6.0.7 on 2026-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='setor',
            field=models.CharField(choices=[('mao_de_obra', 'Mão de obra'), ('insumos', 'Insumos'), ('maquinario', 'Maquinário/equipamentos'), ('transporte', 'Transporte/frete'), ('manutencao', 'Manutenção/infraestrutura'), ('outros', 'Outros')], default='outros', max_length=20),
            preserve_default=False,
        ),
    ]
