# Generated by Django 6.0.7 on 2026-07-31 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_trabalhador'),
        ('plantings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarias_pagas', to='finance.lancamentofinanceiro')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diarias', to='plantings.plantio')),
                ('trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diarias', to='finance.trabalhador')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trabalhador', 'data'), name='unique_diaria_por_trabalhador_e_dia')],
            },
        ),
    ]
