# Generated by Django 6.0.7 on 2026-07-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_diaria'),
        ('plantings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaria',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='diaria',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='plantio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='plantings.plantio'),
        ),
    ]
