# Generated by Django 6.0.7 on 2026-08-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_diaria_options_alter_diaria_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ganho', 'Ganho')], default='gasto', max_length=10),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='setor',
            field=models.CharField(choices=[('mao_de_obra', 'Mão de obra'), ('insumos', 'Insumos'), ('maquinario', 'Maquinário/equipamentos'), ('transporte', 'Transporte/frete'), ('manutencao', 'Manutenção/infraestrutura'), ('venda_colheita', 'Venda de colheita'), ('outros', 'Outros')], max_length=20),
        ),
    ]
