# Generated by Django 6.0.7 on 2026-07-31 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('veneno', 'Veneno'), ('adubo', 'Adubo')], max_length=10)),
                ('carencia_dias', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AplicacaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='plantings.plantio')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='inputs.insumo')),
            ],
        ),
    ]
