# Generated by Django 6.0.7 on 2026-08-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'ordering': ['criado_em']},
        ),
    ]
