# Generated by Django 6.0.7 on 2026-07-31 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('classificacao', models.CharField(choices=[('primeira', 'Primeira'), ('segunda', 'Segunda')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colheitas', to='plantings.plantio')),
            ],
        ),
    ]
