# Generated by Django 6.0.7 on 2026-07-31 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField()),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('colhido', 'Colhido'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantios', to='crops.cultura')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantios', to='properties.talhao')),
            ],
        ),
    ]
