# Generated by Django 6.0.7 on 2026-07-31 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ciclo_dias', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FaseCultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_inicio', models.PositiveIntegerField()),
                ('dia_fim', models.PositiveIntegerField()),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='crops.cultura')),
            ],
            options={
                'ordering': ['dia_inicio'],
            },
        ),
    ]
