# Generated by Django 6.0.7 on 2026-07-31 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='plantings.plantio')),
            ],
        ),
    ]
