# Generated by Django 6.0.7 on 2026-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='notificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
